modLoader = "javafml"
loaderVersion = "[@FORGE_LOADER_MAJOR@,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "codeutilities"
version = "${version}"
displayName = "CodeUtilities"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.codeutilities]]
modId = "forge"
mandatory = true
versionRange = "[@FORGE_LOADER_MAJOR@,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.codeutilities]]
modId = "minecraft"
mandatory = true
versionRange = "[@MINECRAFT@,)"
ordering = "NONE"
side = "BOTH"